// vapn is the community worker command line: install, observe, update,
// pause/resume, and cleanly remove a VAPN worker without touching Docker
// directly. Docker Compose is an implementation detail behind a stable UX.
//
// Everything lives under ~/.vapn (override: VAPN_HOME): config.env, a
// generated docker-compose.yml, and state/ (worker key, identity, snapshot,
// status.json — the file the container writes and this CLI reads).
package main

import (
	"bufio"
	"context"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"github.com/HummingByteDev/vpsa-network-discovery/internal/artifact"
	"github.com/HummingByteDev/vpsa-network-discovery/internal/platform/version"
	"github.com/HummingByteDev/vpsa-network-discovery/internal/worker"
)

const usage = `vapn — VPS Advisor Probe Network worker

Usage: vapn <command>

  install      set up and start a worker (interactive)
  status       worker health at a glance
  doctor       run the system checks
  logs [-f]    worker logs
  pause        stop probing (keeps identity; resume any time)
  resume       start probing again
  update       update to the latest worker image (health-gated, auto-rollback)
  backup       archive worker identity/config to a tar.gz
  unregister   permanently retire this worker with the coordinator
  uninstall    remove everything (offers unregister + config backup)
  version      print CLI version

Home directory: ~/.vapn (override with VAPN_HOME)
`

func home() string {
	if h := os.Getenv("VAPN_HOME"); h != "" {
		return h
	}
	u, err := os.UserHomeDir()
	if err != nil {
		return ".vapn"
	}
	return filepath.Join(u, ".vapn")
}

func stateDir() string    { return filepath.Join(home(), "state") }
func configPath() string  { return filepath.Join(home(), "config.env") }
func composePath() string { return filepath.Join(home(), "docker-compose.yml") }

func die(err error) {
	fmt.Fprintln(os.Stderr, "vapn:", err)
	os.Exit(1)
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprint(os.Stderr, usage)
		os.Exit(2)
	}
	var err error
	switch os.Args[1] {
	case "install":
		err = cmdInstall()
	case "status":
		err = cmdStatus()
	case "doctor":
		_, err = runDoctor(loadConfig(false))
	case "logs":
		err = compose(append([]string{"logs"}, os.Args[2:]...)...)
	case "pause":
		if err = compose("stop", "worker"); err == nil {
			fmt.Println("Worker paused. Assignments redistribute to the fleet within a minute.")
			fmt.Println("Resume any time with: vapn resume")
		}
	case "resume":
		if err = compose("start", "worker"); err == nil {
			fmt.Println("Worker resumed.")
		}
	case "update":
		err = cmdUpdate(len(os.Args) > 2 && os.Args[2] == "--auto")
	case "backup":
		err = cmdBackup()
	case "unregister":
		err = cmdUnregister(true)
	case "uninstall":
		err = cmdUninstall()
	case "version":
		fmt.Println(version.Version)
	default:
		fmt.Fprint(os.Stderr, usage)
		os.Exit(2)
	}
	if err != nil {
		die(err)
	}
}

// --- config ---------------------------------------------------------------

type conf map[string]string

func loadConfig(must bool) conf {
	c := conf{}
	raw, err := os.ReadFile(configPath())
	if err != nil {
		if must {
			die(fmt.Errorf("no worker installed here (%s missing) — run: vapn install", configPath()))
		}
		return c
	}
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if k, v, ok := strings.Cut(line, "="); ok {
			c[k] = v
		}
	}
	return c
}

func (c conf) save() error {
	if err := os.MkdirAll(home(), 0o700); err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("# VAPN worker configuration (managed by `vapn`)\n")
	for _, k := range []string{"VAPN_COORDINATOR_URL", "VAPN_WORKER_NAME",
		"VAPN_SNAPSHOT_PUBLIC_KEY", "VAPN_WORKER_IMAGE", "VAPN_ENROLLMENT_TOKEN"} {
		if v, ok := c[k]; ok && v != "" {
			fmt.Fprintf(&b, "%s=%s\n", k, v)
		}
	}
	return os.WriteFile(configPath(), []byte(b.String()), 0o600)
}

const composeTemplate = `# Generated by vapn — edit config.env, not this file.
name: vapn-worker
services:
  worker:
    image: %s
    restart: unless-stopped
    user: "%d:%d"
    cap_add: [NET_RAW]
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
    env_file: config.env
    environment:
      VAPN_STATE_DIR: /state
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./state:/state
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
`

// writeCompose (re)generates the compose file with the image inlined, so
// every later `docker compose` invocation is self-contained. The container
// runs as the installing user so the bind-mounted state directory (private
// key inside) stays owned by them; unprivileged datagram ICMP works for any
// uid via the ping_group_range sysctl.
func writeCompose(c conf) error {
	return os.WriteFile(composePath(),
		[]byte(fmt.Sprintf(composeTemplate, c["VAPN_WORKER_IMAGE"], os.Getuid(), os.Getgid())), 0o644)
}

func compose(args ...string) error {
	full := append([]string{"compose", "-f", composePath()}, args...)
	cmd := exec.Command("docker", full...)
	cmd.Dir = home()
	cmd.Stdout, cmd.Stderr, cmd.Stdin = os.Stdout, os.Stderr, os.Stdin
	return cmd.Run()
}

func composeQuiet(args ...string) (string, error) {
	full := append([]string{"compose", "-f", composePath()}, args...)
	cmd := exec.Command("docker", full...)
	cmd.Dir = home()
	out, err := cmd.CombinedOutput()
	return strings.TrimSpace(string(out)), err
}

// --- install --------------------------------------------------------------

func prompt(rd *bufio.Reader, label, def string) string {
	if def != "" {
		fmt.Printf("%s [%s]: ", label, def)
	} else {
		fmt.Printf("%s: ", label)
	}
	line, _ := rd.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return def
	}
	return line
}

func cmdInstall() error {
	fmt.Println("VAPN worker setup — you'll need an enrollment token")
	fmt.Println("(create one on your VPS Advisor dashboard under My Workers).")
	fmt.Println()

	c := loadConfig(false)
	rd := bufio.NewReader(os.Stdin)
	hostname, _ := os.Hostname()

	c["VAPN_COORDINATOR_URL"] = prompt(rd, "Coordinator URL", orDefault(c["VAPN_COORDINATOR_URL"], "https://probes.vpsadvisor.com"))
	c["VAPN_WORKER_NAME"] = prompt(rd, "Worker name", orDefault(c["VAPN_WORKER_NAME"], hostname))
	c["VAPN_SNAPSHOT_PUBLIC_KEY"] = prompt(rd, "Snapshot public key", c["VAPN_SNAPSHOT_PUBLIC_KEY"])
	c["VAPN_WORKER_IMAGE"] = orDefault(os.Getenv("VAPN_WORKER_IMAGE"),
		orDefault(c["VAPN_WORKER_IMAGE"], "ghcr.io/hummingbytedev/vapn-worker:latest"))
	if _, err := os.Stat(filepath.Join(stateDir(), "worker.id")); err != nil {
		c["VAPN_ENROLLMENT_TOKEN"] = prompt(rd, "Enrollment token", c["VAPN_ENROLLMENT_TOKEN"])
	}

	fmt.Println("\nSystem check")
	ok, err := runDoctor(c)
	if err != nil {
		return err
	}
	if !ok {
		return fmt.Errorf("system checks failed — fix the ✗ items above and re-run vapn install")
	}

	if err := c.save(); err != nil {
		return err
	}
	if err := os.MkdirAll(stateDir(), 0o700); err != nil {
		return err
	}
	if err := writeCompose(c); err != nil {
		return err
	}

	fmt.Println("\nStarting worker")
	if out, err := composeQuiet("pull"); err != nil {
		// Local/dev images aren't pullable; only fail if it also can't run.
		fmt.Println("  (image pull skipped:", firstLine(out)+")")
	}
	if out, err := composeQuiet("up", "-d"); err != nil {
		return fmt.Errorf("could not start worker: %s", out)
	}

	fmt.Println("Waiting for the worker to come up...")
	st, err := waitStatus(120*time.Second, time.Time{})
	if err != nil {
		fmt.Println("✗ The worker container started but hasn't reported in yet.")
		fmt.Println("  Watch it with: vapn logs -f")
		return nil
	}
	fmt.Println("✓ Registration successful")
	if st.SnapshotVersion != "" {
		fmt.Println("✓ Routing snapshot installed")
	}
	fmt.Println()
	fmt.Printf("Worker ID:\n%s\n\nStatus:\n%s\n\n", st.WorkerID, renderState(st.State))
	switch st.State {
	case "pending":
		fmt.Println("Your worker is awaiting approval. It will begin probing")
		fmt.Println("automatically once approved — nothing more to do.")
	case "active":
		fmt.Println("You are now contributing to the VPS Advisor Probe Network.")
	}
	fmt.Println("\nUseful commands: vapn status · vapn logs -f · vapn pause · vapn update")
	// Token is one-time; drop it from disk after successful registration.
	if st.WorkerID != "" && c["VAPN_ENROLLMENT_TOKEN"] != "" {
		delete(c, "VAPN_ENROLLMENT_TOKEN")
		_ = c.save()
	}
	return nil
}

func orDefault(v, def string) string {
	if v == "" {
		return def
	}
	return v
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}

func renderState(s string) string {
	switch s {
	case "active":
		return "Healthy"
	case "pending":
		return "Awaiting approval"
	default:
		return s
	}
}

func waitStatus(timeout time.Duration, newerThan time.Time) (worker.Status, error) {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		st, err := worker.ReadStatus(stateDir())
		if err == nil && st.WorkerID != "" && st.UpdatedAt.After(newerThan) {
			return st, nil
		}
		time.Sleep(2 * time.Second)
	}
	return worker.Status{}, fmt.Errorf("no status report within %s", timeout)
}

// --- status / doctor ------------------------------------------------------

func cmdStatus() error {
	loadConfig(true)
	st, err := worker.ReadStatus(stateDir())
	if err != nil {
		out, _ := composeQuiet("ps", "--format", "{{.State}}")
		return fmt.Errorf("no status report yet (container: %s) — try: vapn logs", orDefault(out, "not running"))
	}
	stale := time.Since(st.UpdatedAt) > 2*time.Minute
	health := renderState(st.State)
	if stale {
		health = fmt.Sprintf("Unreachable (last report %s ago)", time.Since(st.UpdatedAt).Round(time.Second))
	}
	p := func(k, v string) { fmt.Printf("%-24s%s\n", k+":", v) }
	p("Worker", health)
	p("Worker ID", st.WorkerID)
	p("Software", st.SoftwareVersion)
	p("Coordinator", st.CoordinatorURL)
	p("Routing snapshot", orDefault(st.SnapshotVersion, "not yet installed"))
	p("Last heartbeat", fmt.Sprintf("%s ago", time.Since(st.LastHeartbeatAt).Round(time.Second)))
	p("Assignments", fmt.Sprintf("%d", st.Assignments))
	p("Measurements submitted", fmt.Sprintf("%d", st.MeasurementsSubmitted))
	if !st.LastUploadAt.IsZero() {
		p("Last upload", fmt.Sprintf("%s ago (%d ms)", time.Since(st.LastUploadAt).Round(time.Second), st.LastUploadMillis))
	}
	return nil
}

type check struct {
	name string
	run  func() error
}

func runDoctor(c conf) (bool, error) {
	checks := []check{
		{"Docker CLI", func() error {
			_, err := exec.LookPath("docker")
			return err
		}},
		{"Docker daemon", func() error {
			return exec.Command("docker", "info").Run()
		}},
		{"Docker Compose", func() error {
			return exec.Command("docker", "compose", "version").Run()
		}},
		{"Disk space (≥2 GB free)", func() error { return diskFree(home(), 2<<30) }},
		{"State directory writable", func() error {
			if err := os.MkdirAll(stateDir(), 0o700); err != nil {
				return err
			}
			f := filepath.Join(stateDir(), ".probe")
			if err := os.WriteFile(f, nil, 0o600); err != nil {
				return err
			}
			return os.Remove(f)
		}},
		{"Snapshot public key", func() error {
			_, err := artifact.ParsePublicKey(c["VAPN_SNAPSHOT_PUBLIC_KEY"])
			return err
		}},
		{"Coordinator reachable", func() error { return reachCoordinator(c["VAPN_COORDINATOR_URL"]) }},
		{"Clock synchronization", func() error { return clockSkew(c["VAPN_COORDINATOR_URL"]) }},
	}
	allOK := true
	for _, ck := range checks {
		if err := ck.run(); err != nil {
			fmt.Printf("✗ %s — %v\n", ck.name, err)
			allOK = false
		} else {
			fmt.Printf("✓ %s\n", ck.name)
		}
	}
	return allOK, nil
}

func diskFree(path string, need uint64) error {
	if err := os.MkdirAll(path, 0o700); err != nil {
		return err
	}
	var st syscall.Statfs_t
	if err := syscall.Statfs(path, &st); err != nil {
		return err
	}
	free := st.Bavail * uint64(st.Bsize)
	if free < need {
		return fmt.Errorf("only %d MB free", free>>20)
	}
	return nil
}

func reachCoordinator(url string) error {
	if url == "" {
		return fmt.Errorf("no coordinator URL configured")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 8*time.Second)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, strings.TrimRight(url, "/")+"/api/v1/workers/me", nil)
	if err != nil {
		return err
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	resp.Body.Close()
	// 401 means: reachable, TLS fine, auth required — exactly right.
	if resp.StatusCode >= 500 {
		return fmt.Errorf("coordinator returned %s", resp.Status)
	}
	return nil
}

func clockSkew(url string) error {
	if url == "" {
		return fmt.Errorf("no coordinator URL configured")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 8*time.Second)
	defer cancel()
	req, _ := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	resp.Body.Close()
	server, err := time.Parse(http.TimeFormat, resp.Header.Get("Date"))
	if err != nil {
		return nil // no Date header; not fatal
	}
	skew := time.Since(server)
	if skew < 0 {
		skew = -skew
	}
	if skew > 90*time.Second {
		return fmt.Errorf("clock is %s off — signed requests will be rejected; enable NTP", skew.Round(time.Second))
	}
	return nil
}

// --- update ---------------------------------------------------------------

func cmdUpdate(auto bool) error {
	c := loadConfig(true)
	image := c["VAPN_WORKER_IMAGE"]
	before, _ := imageID(image)
	if out, err := composeQuiet("pull"); err != nil {
		if before == "" {
			return fmt.Errorf("pull failed and no local image present: %s", firstLine(out))
		}
		fmt.Println("Could not check for updates (registry unreachable); keeping the current image.")
		return nil
	}
	after, _ := imageID(image)
	if before == after && before != "" {
		if !auto {
			fmt.Println("Already up to date.")
		}
		return nil
	}
	fmt.Printf("Updating worker image (%s → %s)\n", short(before), short(after))
	restartedAt := time.Now()
	if out, err := composeQuiet("up", "-d"); err != nil {
		return fmt.Errorf("restart failed: %s", out)
	}
	st, err := waitStatus(120*time.Second, restartedAt)
	if err == nil && (st.State == "active" || st.State == "pending" || st.State == "quarantined") {
		fmt.Printf("✓ Update healthy (version %s, state %s)\n", st.SoftwareVersion, st.State)
		return nil
	}
	fmt.Println("✗ Updated worker did not report healthy — rolling back")
	if before == "" {
		return fmt.Errorf("no previous image to roll back to; check vapn logs")
	}
	if err := exec.Command("docker", "tag", before, image).Run(); err != nil {
		return fmt.Errorf("rollback tag failed: %w", err)
	}
	if out, err := composeQuiet("up", "-d", "--force-recreate"); err != nil {
		return fmt.Errorf("rollback start failed: %s", out)
	}
	if _, err := waitStatus(120*time.Second, time.Now()); err != nil {
		return fmt.Errorf("rollback started but worker still unhealthy — check vapn logs")
	}
	fmt.Println("✓ Rolled back to previous image; report this update failure")
	return nil
}

func imageID(image string) (string, error) {
	out, err := exec.Command("docker", "image", "inspect", "--format", "{{.Id}}", image).Output()
	return strings.TrimSpace(string(out)), err
}

func short(id string) string {
	id = strings.TrimPrefix(id, "sha256:")
	if len(id) > 12 {
		return id[:12]
	}
	if id == "" {
		return "none"
	}
	return id
}

// --- backup / unregister / uninstall --------------------------------------

func cmdBackup() error {
	loadConfig(true)
	out := fmt.Sprintf("vapn-worker-backup-%s.tar.gz", time.Now().UTC().Format("20060102T150405Z"))
	cmd := exec.Command("tar", "czf", out, "-C", filepath.Dir(home()), filepath.Base(home()))
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		return err
	}
	fmt.Printf("Backup written: %s\n", out)
	fmt.Println("It contains this worker's PRIVATE KEY — store it like a password.")
	return nil
}

func cmdUnregister(confirm bool) error {
	c := loadConfig(true)
	if confirm {
		fmt.Println("Unregistering permanently retires this worker's identity.")
		fmt.Print("Type 'retire' to continue: ")
		rd := bufio.NewReader(os.Stdin)
		line, _ := rd.ReadString('\n')
		if strings.TrimSpace(line) != "retire" {
			return fmt.Errorf("aborted")
		}
	}
	st := worker.State{Dir: stateDir()}
	key, err := st.Key()
	if err != nil {
		return fmt.Errorf("no worker identity found: %w", err)
	}
	id, err := st.WorkerID()
	if err != nil || id == "" {
		return fmt.Errorf("this worker never registered")
	}
	client := worker.NewClient(c["VAPN_COORDINATOR_URL"], key).WithID(id)
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()
	if err := client.Retire(ctx); err != nil {
		return fmt.Errorf("retire failed: %w", err)
	}
	_ = compose("stop", "worker")
	fmt.Println("Worker retired. Thank you for contributing!")
	return nil
}

func cmdUninstall() error {
	loadConfig(true)
	rd := bufio.NewReader(os.Stdin)
	fmt.Print("Also unregister the worker with the coordinator? [Y/n]: ")
	ans, _ := rd.ReadString('\n')
	if a := strings.ToLower(strings.TrimSpace(ans)); a == "" || a == "y" || a == "yes" {
		if err := cmdUnregister(false); err != nil {
			fmt.Println("  (unregister failed:", err, "— continuing with removal)")
		}
	}
	fmt.Print("Keep a backup of the configuration and identity? [Y/n]: ")
	ans, _ = rd.ReadString('\n')
	if a := strings.ToLower(strings.TrimSpace(ans)); a == "" || a == "y" || a == "yes" {
		if err := cmdBackup(); err != nil {
			return fmt.Errorf("backup failed (aborting uninstall): %w", err)
		}
	}
	if out, err := composeQuiet("down", "--rmi", "all"); err != nil {
		fmt.Println("  (compose down:", firstLine(out)+")")
	}
	if err := os.RemoveAll(home()); err != nil {
		return err
	}
	fmt.Println("VAPN worker removed. No orphaned resources remain.")
	fmt.Println("(This binary itself: remove with `sudo rm $(which vapn)`.)")
	return nil
}
